/**
 * Unit Tests for userController.js
 * Generated by Unit Test Generator Agent
 * Bug: API-404
 * Date: 2026-02-24
 * 
 * Following FIRST principles:
 * - Fast: No I/O, mocked responses
 * - Independent: Each test self-contained
 * - Repeatable: Deterministic, fixed data
 * - Self-validating: Clear assertions
 * - Timely: Tests the specific bug fix
 */

// Import the controller directly to test the logic
const { getUserById, getAllUsers } = require('../src/controllers/userController');

// Mock response object factory
const createMockRes = () => {
  const res = {};
  res.status = jest.fn().mockReturnValue(res);
  res.json = jest.fn().mockReturnValue(res);
  return res;
};

// Mock request object factory
const createMockReq = (params = {}) => ({
  params
});

describe('userController', () => {
  
  describe('getUserById', () => {
    
    // ==========================================
    // BUG FIX VERIFICATION TESTS
    // These tests verify the API-404 fix works
    // ==========================================
    
    describe('bug fix verification (API-404)', () => {
      
      test('should find user when ID is passed as string "123" (simulating URL param)', async () => {
        // Arrange - URL params are always strings
        const req = createMockReq({ id: '123' });
        const res = createMockRes();
        
        // Act
        await getUserById(req, res);
        
        // Assert - should return user, not 404
        expect(res.json).toHaveBeenCalledWith({
          id: 123,
          name: 'Alice Smith',
          email: 'alice@example.com'
        });
        expect(res.status).not.toHaveBeenCalledWith(404);
      });

      test('should find user when ID is passed as string "456"', async () => {
        const req = createMockReq({ id: '456' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        expect(res.json).toHaveBeenCalledWith({
          id: 456,
          name: 'Bob Johnson',
          email: 'bob@example.com'
        });
      });

      test('should find user when ID is passed as string "789"', async () => {
        const req = createMockReq({ id: '789' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        expect(res.json).toHaveBeenCalledWith({
          id: 789,
          name: 'Charlie Brown',
          email: 'charlie@example.com'
        });
      });
    });

    // ==========================================
    // HAPPY PATH TESTS
    // ==========================================
    
    describe('happy path', () => {
      
      test('should return user object with correct structure', async () => {
        const req = createMockReq({ id: '123' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        const returnedUser = res.json.mock.calls[0][0];
        expect(returnedUser).toHaveProperty('id');
        expect(returnedUser).toHaveProperty('name');
        expect(returnedUser).toHaveProperty('email');
      });

      test('should return numeric id in response (not string)', async () => {
        const req = createMockReq({ id: '123' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        const returnedUser = res.json.mock.calls[0][0];
        expect(typeof returnedUser.id).toBe('number');
      });
    });

    // ==========================================
    // EDGE CASE TESTS
    // ==========================================
    
    describe('edge cases', () => {
      
      test('should return 404 for non-existent user ID', async () => {
        const req = createMockReq({ id: '999' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        expect(res.status).toHaveBeenCalledWith(404);
        expect(res.json).toHaveBeenCalledWith({ error: 'User not found' });
      });

      test('should return 404 for non-numeric string ID', async () => {
        const req = createMockReq({ id: 'abc' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        // parseInt('abc', 10) returns NaN, which won't match any user
        expect(res.status).toHaveBeenCalledWith(404);
        expect(res.json).toHaveBeenCalledWith({ error: 'User not found' });
      });

      test('should return 404 for empty string ID', async () => {
        const req = createMockReq({ id: '' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        expect(res.status).toHaveBeenCalledWith(404);
      });

      test('should return 404 for negative ID', async () => {
        const req = createMockReq({ id: '-1' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        expect(res.status).toHaveBeenCalledWith(404);
      });

      test('should handle ID with leading zeros', async () => {
        const req = createMockReq({ id: '0123' });
        const res = createMockRes();
        
        await getUserById(req, res);
        
        // parseInt('0123', 10) = 123, should find Alice
        expect(res.json).toHaveBeenCalledWith({
          id: 123,
          name: 'Alice Smith',
          email: 'alice@example.com'
        });
      });
    });
  });

  // ==========================================
  // getAllUsers TESTS (unchanged by fix, but verify no regression)
  // ==========================================
  
  describe('getAllUsers', () => {
    
    test('should return array of all users', async () => {
      const req = createMockReq();
      const res = createMockRes();
      
      await getAllUsers(req, res);
      
      expect(res.json).toHaveBeenCalled();
      const users = res.json.mock.calls[0][0];
      expect(Array.isArray(users)).toBe(true);
      expect(users).toHaveLength(3);
    });

    test('should return users with correct structure', async () => {
      const req = createMockReq();
      const res = createMockRes();
      
      await getAllUsers(req, res);
      
      const users = res.json.mock.calls[0][0];
      users.forEach(user => {
        expect(user).toHaveProperty('id');
        expect(user).toHaveProperty('name');
        expect(user).toHaveProperty('email');
      });
    });

    test('should include all known users', async () => {
      const req = createMockReq();
      const res = createMockRes();
      
      await getAllUsers(req, res);
      
      const users = res.json.mock.calls[0][0];
      const ids = users.map(u => u.id);
      expect(ids).toContain(123);
      expect(ids).toContain(456);
      expect(ids).toContain(789);
    });
  });
});
